variables:
    TZ: "America/New_York"
    # Configure postgres service (https://hub.docker.com/_/postgres/)
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    APT_CACHE_DIR: "$CI_PROJECT_DIR/apt-cache"
    DEBIAN_FRONTEND: noninteractive
    IMAGE_TAG: 'egrep -o "[0-9]\.([0-9]|[0-9][0-9])(\.[0-9])?" faraday/__init__.py'
    VAULT_ROLE: 'faraday-readonly'
    VAULT_ADDR: 'https://tluav-lb.faradaysec.com'

    ## ENV_VARS LIST
    # FULL_TEST = Test all jobs
    # BUILD_TEST = Test default and build jobs
    # DAILY_TEST = Run every night at 03 am
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"
    - "$CI_PROJECT_DIR/apt-cache"

before_script:
    - mkdir -pv $APT_CACHE_DIR

include:
  - local: .gitlab/ci/fetch-secrets.yaml
  - local: .gitlab/ci/.rules-conditions.yml


  - local: .gitlab/ci/testing/.pretesting-gitlab-ci.yml
  - local: .gitlab/ci/testing/.nix-testing-gitlab-ci.yml
  - local: .gitlab/ci/testing/.venv-testing-gitlab-ci.yml
  - local: .gitlab/ci/testing/.hypothesis-nix-gitlab-ci.yml
  # - local: .gitlab/ci/testing/.posttesting-gitlab-ci.yml

  - local: .gitlab/ci/build-ci/.prebuild-gitlab-ci.yml
  - local: .gitlab/ci/build-ci/.build-gitlab-ci.yml
  - local: .gitlab/ci/build-ci/.testing-gitlab-ci.yml

  - local: .gitlab/ci/upload/.storage-gitlab-ci.yml

  - local: .gitlab/ci/deploy/deploy-gitlab-ci.yml

  - local: .gitlab/ci/publish/.set-tag-gitlab-ci.yml
  - local: .gitlab/ci/publish/.mirror-to-github-gitlab-ci.yml
  - local: .gitlab/ci/publish/.docker-publish-gitlab-ci.yml

  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
    - pre_testing
    - test
    # - post_testing
    - pre_build
    - build
    - build_testing
    - upload
    - upload_testing
    - deploy
    - publish

services:
    - postgres:latest
    - redis:latest
