default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.9.0]
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.56'
    hooks:
    -   id: flynt
        args: [ -df ]
-   repo: local
    hooks:
    -   id: sanity-check
        name: Commit SanityCheck
        entry: bash scripts/sanity_check_commit.sh
        language: system
        verbose: true
        stages: [merge-commit, commit, push]
    -   id: sanity-check-file
        name: File SanityCheck
        entry: scripts/sanity_check_file.py
        language: python
        verbose: true
        pass_filenames: false
        args: [--mode=diff]
        stages: [merge-commit, commit]
    -   id: sanity-check-file-push
        name: File Push SanityCheck
        entry: scripts/sanity_check_file.py
        language: python
        verbose: true
        pass_filenames: false
        args: [--mode=ls, --local]
        stages: [push]
